### ISSUE TITLE
How to use SelemId::new?

### ISSUE THREAD

**Issue by herzplatinedurchgebrannt** [diwic/alsa-rs#105]
Hello!
I just started learning Rust and Alsa and I am trying to access my audio interface (Focusrite Scarlett 18i8 2.gen).
My goal is to have a simple Rust program that can make changes to the interfaces mixer (e.g. muting channel 1, ...).

I started with the following lines to access the interface:

```
let mixer: Mixer  = Mixer::new("hw:3", false).unwrap();
let sid: SelemId    = SelemId::new("????", 0);
let selem: Selem = mixer.find_selem(&sid).expect("Coundn't find SelemId");
```

The code fails trying to find the selem. I dont know which values are expected of the SelemId. 
Is this the name/index of an mixer element? 
Where can I get these infos?

Thank you in advance!

**Comment by herzplatinedurchgebrannt** [comment]
Strange: on my hw:1 device (which is not the scarlett), its working:

`    let c = Card::new(3);

    println!("{:#?}", c.get_name());
    println!("{:#?}", c.get_index());
    println!("{:#?}", c.get_longname());

    let mixer: Mixer  = Mixer::new("hw:1", false).unwrap();
    let sid: SelemId  = SelemId::new("Capture", 0);

    
    let selem: Selem = mixer.find_selem(&sid).unwrap();`

"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:16:47"

**Comment by herzplatinedurchgebrannt** [comment]
Now i got it on my own:

The code was okay, I recognized that my HW:3 (Scarlett device) has no element with the name "Master". Instead it has e.g. "Line 01 (Monitor L)".

I found the element names inside of alsamixer. Press F6 to change the soundcard.

Thanks anyway!

**Comment by diwic** [comment]
You can also use `Mixer::Iter` to get a list of all Elem/Selem. https://docs.rs/alsa/latest/alsa/mixer/struct.Mixer.html#method.iter
