### ISSUE TITLE
Tag off a release?

### ISSUE THREAD

**Issue by chadmed** [diwic/alsa-rs#106]
Hi,

We're looking to release software dependent on this crate, however find ourselves
having to carry a downstream branch frozen at `2fec79bd4cbf`. This is obviously
not ideal. Would it be possible to tag off a release so that we can get rid of our
downstream branch and use the crate properly?

Thanks :)

**Comment by diwic** [comment]
Enjoy! 

I was a little slow on replying due to vacation times.
