### ISSUE TITLE
Support Creating an Hctl from a Ctl via snd_hctl_open_ctl

### ISSUE THREAD

**Issue by naftulikay** [diwic/alsa-rs#108]
I'm currently working on a project that uses this crate heavily, much thanks for all the hard work.

I am currently using the following logic to obtain a `HCtl` instance:

```rust
use alsa::{Ctl, HCtl};
use alsa::card::{Iter as CardIter};

let mut card_iter = CardIter::new();

while let Some(Ok(card)) = card_iter.next() {
    let ctl = Ctl::from_card(&card, true).unwrap();
    let hctl = HCtl::new(format!("hw:{}", card.get_index()).as_str(), true).unwrap();

    // do work
}
```

Fetching a `HCtl` instance from the device name is error-prone perhaps, as there's no direct way to go from a `Card` instance to an `HCtl` instance. It's possible to go from `Card` to `Ctl` using `Ctl::from_card`, but no way to go from either `Card` or `Ctl` to `HCtl`. 

[In the underlying `alsa-sys` crate](https://docs.rs/alsa-sys/0.3.1/alsa_sys/fn.snd_hctl_open_ctl.html), and thus the C library, [`snd_hctl_open_ctl`](https://www.alsa-project.org/alsa-doc/alsa-lib/group___h_control.html#ga48b556b219e99c36d65efc6b8a97029c) allows creation of a `snd_hctl_t` handle from an existing `snd_ctl_t`. Therefore, it shouldn't be too difficult to implement a method like `HCtl::from_ctl` to make it easier to get a `HCtl` from a `Ctl`.

I may be able to contribute some work here, but it will have to wait a few days at best.

**Comment by diwic** [comment]
I had a look on how Ctl::from_card is implemented and decided to implement HCtl::from_card the same way. Using `hw:{}`-strings is the way to go, I would say.

**Comment by diwic** [comment]
As a side note, looking at the code for snd_hctl_open_ctl, it seems to consume the ctl handle. If you feel the need for such a function feel free to send a PR.

**Comment by naftulikay** [comment]
Thank you so much! I greatly appreciate it.
