### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by naftulikay** [diwic/alsa-rs#109]
Sorry for opening an issue for this, but I wanted to reach out to discuss how I might be able to contribute to this crate in terms of documentation and code. If you're on discord, my username is `naftulikay`, if email works better, you can reach me at `me` AT my first name DOT `w t f`. Tried emailing at your ubuntu email address but it wouldn't route through. I'm also `@naftulikay` on twitter if that's a preferred method of communication.

**Comment by diwic** [comment]
Sorry for the slow reply - been off grid on holiday.

Contributions are very welcome 🙂
If contributions follow existing conventions (e g, adding missing methods), just send a PR. Larger suggestions/ideas are better discussed in an issue first.

Does that make sense?

**Comment by diwic** [comment]
Yeah so github is preferred method, but the email address in Cargo.toml should work also.
