### ISSUE TITLE
Passing PCM handles between threads

### ISSUE THREAD

**Issue by mbr** [diwic/alsa-rs#11]
I'm not very familiar with the ALSA API, but the way I interpret http://www.alsa-project.org/main/index.php/SMP_Design, it seems that it is possible to send PCM handles across thread boundaries?

In a very simple application with a single audio thread, I'd love to be able to open the PCM device in the main thread, that way I don't have to propagate open/hwparam errors/unwraps back.

 However, since `*mut alsa_sys::snd_pcm_t` isn't `Send`, neither is `alsa::PCM`, among other things because no explicit `Send` implementation has been added.

While `PCM` is definitely not `Sync`, I think `Send` fits?

**Comment by diwic** [comment]
I think you're right. A look at the alsa-lib source code didn't seem to contradict this either, so I've now implemented that. Enjoy!
