### ISSUE TITLE
Can pcm::IO<S> be Send?

### ISSUE THREAD

**Issue by anatawa12** [diwic/alsa-rs#111]
I want to use `pcm::IO<S>` as send in async closure but not. What's the reason for that?

```
async fn test() {
    tokio::spawn(async move {
        const SAMPLE_RATE: u32 = 48000;
        const BIT_RATE: i32 = 28_000;
        const FRAME_MS: u32 = 20;

        let pcm = PCM::new("plughw:1,0", Direction::Capture, false)?;
        {
            let params = HwParams::any(&pcm).unwrap();
            params.set_rate_resample(true)?;
            params.set_access(Access::RWInterleaved)?;
            params.set_channels(1)?;
            params.set_rate(SAMPLE_RATE, ValueOr::Nearest)?;
            params.set_format(Format::s16())?;
            pcm.hw_params(&params)?;
        }

        pcm.prepare()?;

        let io = pcm.io_i16()?;

        while true { // some condition
            let mut buffer = [0i16; (SAMPLE_RATE / (1000 / FRAME_MS)) as usize];
            let read = io.readi(&mut buffer)?;
            //let read = pcm.io_i16()?.readi(&mut buffer)?; // if I use this code instead, no compile errors
            let buffer = &buffer[..read];

            process_async(buffer).await;
        }

        drop(pcm); // close

        Result::<()>::Ok(())
    });
}

async fn process_async(p0: &[i16]) {
    todo!()
}
```

**Comment by diwic** [comment]
Hmm, so what I want to prevent here is calling into the alsa library in parallel for two different threads (for the same PCM object), alsa does not support that. 
If  `pcm::IO<S>` was `Send`, then one could potentially move the io object into another thread and then call both an io function and an pcm function in parallel. Right?

**Comment by anatawa12** [comment]
> If  pcm::IO<S> was Send, then one could potentially move the io object into another thread and then call both an io function and an pcm function in parallel. Right?

Yes

I wanted to remove spammy calling hw_params but it looks impossible with safe rust. Thank you.

**Comment by diwic** [comment]
@anatawa12 
I guess it would be possible to create a `unsafe fn IO::new_unchecked()` that skips the `hw_params_current` and the `check_has_io` calls. Would you like to write a PR for that?
