### ISSUE TITLE
Error 77 trying to retrieve HW params from pcm device

### ISSUE THREAD

**Issue by JulienH2000** [diwic/alsa-rs#122]
Hello,
I'm having trouble with the Ravenna driver and the ALSA API.
Using Alsa-rs rust bindings of the Alsa C library, once instancing the ravenna driver as a new alsa::PCM device, it fails to retrieve the device parameters (using snd_pcm_hw_params_current C function binding).
Here's the Cargo error returned :
<code>called `Result::unwrap()` on an `Err` value: ALSA function 'snd_pcm_hw_params_current' failed with error 'Unknown errno (77)'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.</code>

And here's a snippet of the code :
<code>  

    pub fn new_ip (label: String) -> Self {
        let new_pcm = alsa::PCM::new("hw:CARD=RAVENNA,DEV=0", Direction::Capture, false).unwrap();
        let hwp = new_pcm.hw_params_current().unwrap();
        //let hwp = HwParams::any(&new_pcm).unwrap();
        println!("HwP : {:?}\n", hwp);
        let leg_width = hwp.get_channels().unwrap();
        let format = hwp.get_format().unwrap();
        let buffer_size = hwp.get_buffer_size().unwrap();
        let _ = new_pcm.drop();

        return pcm_device {
            label: label,
            direction: Direction::Capture,
            alsa_pcm: alsa::PCM::new("hw:CARD=RAVENNA,DEV=0", Direction::Capture, false).unwrap(),
            leg_width: leg_width,
            format: format,
            buffer_size: buffer_size,
        }
    }  
</code>

Note that the same error occurs in both capture and playback.

Also, something I can't figure is that all examples seems to set hardware parameters before doing anything, but what if I just whats to retrieve the parameters set beforehand elsewhere ? 

I'm using bondagit's Merging Ravenna ALSA driver. 

Thanks !

**Comment by diwic** [comment]
Hi,

When the device is first opened, it has no hwparams set, so it returns an error. 
E g, you can't retreive the current buffer size if there is no buffer at all, which is the case if you have not set any hwparams. 

Does that make sense?

**Comment by JulienH2000** [comment]
Hello !
I'm ok with the logic of it, but in my case i'm settings the parameters (buffer, sample rate, bit depth etc....) externally, so I don't want my piece of software to interfer with my driver settings...
Does this my sense ? Or am I taking the wrong path here ? 
If I have to set the parameters from rust it means that I have to bypass my driver daemon... 
thanks a lot !

**Comment by diwic** [comment]
When you call `HwParams::any`, a well implemented driver should constrain the configuration space. E g, if the driver only allows 48kHz, then `get_rate`, `get_rate_min` and `get_rate_max` should both return 48000. Not 100% sure but I believe you don't need to call `set_rate` at all in that case.

So basically, if *all* parameters are fixed by the driver, then this could work:

    let hwp = HwParams::any(&new_pcm).unwrap();
    pcm.hw_params(&hwp).unwrap();

It's likely though that you still need to set a parameter or two.

Do some experiments and see what `HwParams::any` returns. Both because it depends a lot on how the driver is written, and because I'm not sure exactly what to do here.

**Comment by diwic** [comment]
@JulienH2000  I'm not familiar with this particular driver. If you want info on how this particular driver works with ALSA, then ask the bondagit people. I'm merely maintaining rust bindings to the ALSA library.
