### ISSUE TITLE
io_i32_s24() wavefolding issue

### ISSUE THREAD

**Issue by JulienH2000** [diwic/alsa-rs#126]
Hello,
I've been fighting for a bit against some strange behavior of my DSP. 
My audio pipeline is working fine from end to end, but in certain condition, the audio is awful.
Going deeper, I noticed these :
"output = input" -> Perfect Audio
"output = 1.0001 * input" -> Perfect Audio
"output = 0.98 * input" -> Massive distortion
"output = 0.7 * input" -> Extreme distortion, original audio unrecognizable

After a lot of tests and audio sample data analyze, I think I'm onto something : 
the io_i32_s24 method, for some reason, doesn't support the negative value of the signal, so it produces a signal where all the negative parts of the signal are flipped and mapped at the max value of the 32 bits integer. 
Thus, it produced a signal highly incompatible with any linear signal processing, even a simple multiplication outbound this top negative part, and wrecks everything...
Clearly both read and write use this method, so input straight to output is working perfectly fine.

The i16 handles fine the negative values in both read & write. (The synth example of the repo is written with i16 for example, but it surely won't work with i32_s24).

I'm attaching some plotting of the data I have gathered, I can provide more if needed. 

Maybe I'm clueless and this is a normal behavior, but to me this crate is unusable with 24 bits PCM audio.....
Don't hesitate, if you needed any more data or tests.
Thanks a lot
![Sine 440 i32 vs i16](https://github.com/user-attachments/assets/25e8fed0-31ad-4df3-a49f-d24ffe722242)
![detailed i32](https://github.com/user-attachments/assets/5b2f7239-b445-4d4b-8942-3f94472beb36)
![i32 In vs In * coef](https://github.com/user-attachments/assets/00a8bfd8-1f7c-402a-93d7-38a1395cde4f)
![i32 Sine 440](https://github.com/user-attachments/assets/4967ecca-67b8-46f5-8de0-5997f79dd4a6)

**Comment by diwic** [comment]
The first plot shows input in s24 format with a zero byte in between. I don't have a better solution for this than to manually process input samples with the formula `if s >= 2^23 { s - 2^24 } else { s }`. 

Outputs is likely unaffected by this problem, the fourth byte will be ignored so it does not matter. Is that consistent with your findings?
