### ISSUE TITLE
Error: explicit destructor calls not allowed

### ISSUE THREAD

**Issue by joerg-krause** [diwic/alsa-rs#14]
When using `pcm.drop()` the Rust compilers fails with:

```
error[E0040]: explicit use of destructor method

     |
1011 |                 { let pcm = self.0.as_mut().unwrap(); pcm.drop().unwrap(); }
     |                                                           ^^^^ explicit destructor calls not allowed

```

**Comment by diwic** [comment]
I can't reproduce here - `pcm.drop()` correctly shadows the one in the `Drop` trait. Probably your  `pcm` variable is not a `PCM` but something else?

**Comment by joerg-krause** [comment]
I checked the type, it is ``&mut alsa::PCM`.

**Comment by joerg-krause** [comment]
Using `as_ref()` instead `as_mut()` does work.
