### ISSUE TITLE
Why is PortSubscribe::new() private?

### ISSUE THREAD

**Issue by Boddlnagg** [diwic/alsa-rs#18]
Is there a reason why `PortSubscribe::new()` is private? I can use `PortSubscribe::empty()` instead, but I'm not sure what's the difference.

**Comment by Boddlnagg** [comment]
Looking at the implementation, I see that `empty()` calls `new()` internally and zeroes the memory. This should be documented. Maybe `new()` should be public, but `unsafe`?

**Comment by diwic** [comment]
One of the design goals of alsa-rs is for it to be "tiny but safe". I prefer not to expose unsafe functions unless a very good reason to do so.
