### ISSUE TITLE
Document MidiEvent::encode

### ISSUE THREAD

**Issue by Boddlnagg** [diwic/alsa-rs#19]
`MidiEvent::encode` really needs documentation as to what it does.

From the signature and the implementation I can see that it returns (in case of success) the number of bytes consumed from the buffer as well as the encoded event (or `None` if no complete message was encoded).

Then it also needs to be documented that the event buffer is copied for long (sysex) messages. I guess this is because the documentation of [`snd_midi_event_encode`](http://www.alsa-project.org/alsa-doc/alsa-lib/group___m_i_d_i___event.html#gae44531e8091bdd6e97a5b70e7b81ea10) states that

> When this function returns a system exclusive sequencer event (ev->type is SND_SEQ_EVENT_SYSEX), the data pointer (ev->data.ext.ptr) points into the MIDI event parser's buffer. Therefore, the sequencer event can only be used as long as that buffer remains valid, i.e., until the next call to snd_midi_event_encode, snd_midi_event_encode_byte, snd_midi_event_resize_buffer, snd_midi_event_init, snd_midi_event_reset_encode, or snd_midi_event_free for that MIDI event parser.

This makes me wonder whether it might be possible to encode this in the Rust typesystem using lifetimes, instead of requiring a copy?

Furthermore, the documentation of [`snd_seq_event_input`](http://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_event.html#ga6421feafcd6f116d34531d6b54177c17) (where currently the data is also copied by `Event::extract`) has no such comment, which makes me wonder if the buffer there is managed by the event itself (because there is no separate underlying buffer).

**Comment by Boddlnagg** [comment]
Some more comments about `snd_seq_event_input`: If I understand this correctly, incoming SysEx messages are copied at least three times when I try to integrate the currently implemented API in midir. 
- The first copy happens in [`Seq::event_input`](https://github.com/diwic/alsa-rs/blob/1121de7e8a5c83230f2b2e7495658380d63f9c00/src/seq.rs#L125), or more concretely in the `to_vec` call [here](https://github.com/diwic/alsa-rs/blob/1121de7e8a5c83230f2b2e7495658380d63f9c00/src/seq.rs#L470).
- The second copy happens when I get the data from the event (`clone` [here](https://github.com/diwic/alsa-rs/blob/1121de7e8a5c83230f2b2e7495658380d63f9c00/src/seq.rs#L590)).
- The third copy (which is probably preventable) happens because I'm collecting the messages into a new buffer for the case that they are longer than 256 bytes, because a comment in RtMidi indicates that ALSA segments messages in this case. I'm trying to find out if this is actually the case, or if SysEx events are always buffered internally when decoding, until they are complete (they need to be terminated with a `0xF7` byte).

Ideally I want to copy the data only once out of the event structure returned from ALSA and into the vector/buffer passed to the user of midir.

**Comment by Boddlnagg** [comment]
The solution with the callback certainly improves the situation, thanks! Still, do you think that a solution with lifetimes might be possible? I could experiment with that a little bit if you're not opposed, but I wanted to ask before wasting time there.

**Comment by diwic** [comment]
There are two problems with the lifetimes as I see it: 
 * AFAICS, snd_seq_event_input does not properly document how long the buffer is valid, so it's not easy to know what lifetime actually applies
 * changing `Event` to `Event<'a>` makes working with events in general a lot less ergonomic.

...or did you have something else in mind?

**Comment by Boddlnagg** [comment]
No, it would involve changing `Event` to `Event<'a>` and probably some other more complicated types. You're probably right that it's not worth the effort. I'm fine with the current situation.

**Comment by diwic** [comment]
@Boddlnagg btw, you probably want to use [extend_from_slice](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend_from_slice) instead of pushing each byte individually [here](https://github.com/Boddlnagg/midir/blob/master/src/backend/alsa/mod.rs#L659) :-)

**Comment by Boddlnagg** [comment]
I've already changed that in my [branch](https://github.com/Boddlnagg/midir/blob/alsa-rs/src/backend/alsa/mod.rs#L708) where I integrade alsa-rs ;-)

However, SysEx messages currently don't work in that branch. I'm getting a segfault when reading the backing buffer after event encoding. Currently investigating ...

**Comment by diwic** [comment]
Ok, I can reproduce that segfault here, so it's not on your side. I'll have a look.

**Comment by diwic** [comment]
The problem is in alsa-sys. The pointer is 64-bit (I assume you're on 64-bit too)? 

    (gdb) print zz
    $7 = (struct snd_seq_ev_ext_t *) 0x7ffff65fdd38
    (gdb) print &zz.ptr
    $8 = (enum class c_void **) 0x7ffff65fdd40

These are 8 bytes apart and the 64-bit pointer is 8 bytes as well, but https://docs.rs/alsa-sys/0.1.1/alsa_sys/struct.Union_Unnamed10.html is just 12 bytes in total.

**Comment by diwic** [comment]
The question is now whether Union_Unamed10 should actually be 16 bytes, or if there should not be 4 bytes of padding between ext.len and ext.ptr...

**Comment by diwic** [comment]
So the answer is 12 bytes, because snd_seq_ev_ext has "attribute packed":

    struct snd_seq_ev_ext {
            unsigned int len;               /**< length of data */
            void *ptr;                      /**< pointer to data (note: can be 64-bit) */
    } __attribute__((packed));

**Comment by Boddlnagg** [comment]
Yeah, I've just come to the same conclusion. Will you send a PR to [alsa-sys](https://github.com/tomaka/cpal/tree/master/alsa-sys)?

**Comment by diwic** [comment]
Meanwhile, I pushed a workaround to this repository.

**Comment by Boddlnagg** [comment]
Thanks! By the way, when I encode a SysEx event, then send it using `event_output`(http://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_event.html#ga0360e41b946c9948ad717beef7c5ab61), the buffer pointer in the event needs to be valid, right? So the copy created while encoding is of no use. This might really require lifetimes after all ...

**Comment by Boddlnagg** [comment]
I can confirm that your workaround fixes the segfault for me.

**Comment by diwic** [comment]
Set_data clones the Vec, then sets the buffer pointer to its internal clone. The internal clone is valid for as long as the Event is.

**Comment by Boddlnagg** [comment]
But if I'm not mistaken, `set_data` is never called on that code path (I'm only calling `encode`, followed by `event_output`).

**Comment by diwic** [comment]
Good catch. Fixed.
