### ISSUE TITLE
Calling EventData methods directly should be unsafe

### ISSUE THREAD

**Issue by Boddlnagg** [diwic/alsa-rs#21]
For example, the following is safe today, but shouldn't be:
```rust
let ev = ... // some event that is not a `Connect` event
let connect = <Connect as EventData>::get_data(&ev)
```

**Comment by diwic** [comment]
I gave this a thought when I wrote the API, but I think it's safe. You might get bogus values, but nothing *unsafe* in terms of what Rust means with memory unsafety. Are you sure?

**Comment by Boddlnagg** [comment]
I'm not totally sure ... I'll give it another thought and see whether I can come up with a real example of memory unsafety.

**Comment by diwic** [comment]
Hmm, maybe if you do `Event::new(..., Vec)` and then overwrite that vec with something that is not a pointer, alsa will not be happy...

**Comment by Boddlnagg** [comment]
I think the commit that closed this issue was unrelated (it was related to the discussion in #19 instead). The idea in your previous comment is the main issue, I think. You can send an event with arbitrary data to ALSA and have ALSA interpret it as a len/ptr pair, which involves dereferencing an arbitrary value and is memory unsafe.

**Comment by diwic** [comment]
> You can send an event with arbitrary data to ALSA and have ALSA interpret it as a len/ptr pair,

This is no longer possible as event_output (and a few more) sets len/ptr right before the call to alsa.

**Comment by Boddlnagg** [comment]
I see ... you were probably right to close this issue, then! 😃
