### ISSUE TITLE
Wrap snd_seq_control_queue

### ISSUE THREAD

**Issue by Boddlnagg** [diwic/alsa-rs#22]
This is a follow-up after #16, because I took some time now to look at it. And I'm impressed, the current version contains *almost* everything that I needed, awesome work! :+1: 

I'm missing only one function: [`snd_seq_control_queue`](http://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_middle.html#ga36dee7982baa47ad22ab8437541ea5ef). Actually I'm using `snd_seq_start_queue` and `snd_seq_stop_queue`, but those are defined as macros in the original API (wrapping `snd_seq_control_queue`).  Maybe you can create functions for them also.

**Comment by diwic** [comment]
snd_seq_start_queue is just a simple wrapper around:

    let mut e = Event::new(EventType::Start, EvQueueControl { queue: queue, value: () });
    seq.snd_seq_event_output(&mut e);

**Comment by Boddlnagg** [comment]
Okay ... this was not immediately clear to me from the documentation of [`snd_seq_control_queue`](http://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_middle.html#ga36dee7982baa47ad22ab8437541ea5ef). I looked at the [implementation](https://github.com/mikelima/alsa-lib/blob/master/src/seq/seqmid.c#L48-L58) and I'm still not quite sure if it's equivalent, because of the `set_direct` call (I'm using the code path where `ev == NULL`). I admit that I don't understand all the details, because I originally the midir code is a port of RtMidi, which I did rather mechanically without studying the ALSA documentation in depth.

**Comment by diwic** [comment]
Right, it's a wrapper around:

    let mut e = Event::new(EventType::Start, EvQueueControl { queue: queue, value: () });
    e.set_direct();
    seq.snd_seq_event_output(&mut e);

**Comment by Boddlnagg** [comment]
There is no `set_dest` for `Event` ...

**Comment by diwic** [comment]
Look again :tada:

**Comment by Boddlnagg** [comment]
> ... neither is there a public constructor for EvQueueControl

Sorry, I had edited the post ;-) I hope you're not too annoyed with all my comments?

**Comment by diwic** [comment]
Not annoyed, rather pleased that someone reviews my code, especially since you point out valid/relevant things. EvQueueControl fields are now public.

**Comment by Boddlnagg** [comment]
Okay, I consider this issue solved, but I'd still prefer a direct wrapper of `snd_seq_control_queue` in the case someone is porting code to Rust and does not know the details of what this function actually does.
