### ISSUE TITLE
Add support for set_callback

### ISSUE THREAD

**Issue by antoyo** [diwic/alsa-rs#27]
Hello.
It would be nice to have an API to know when the volume changes (using [`snd_mixer_set_callback`](http://www.alsa-project.org/alsa-doc/alsa-lib/group___mixer.html#ga691a593ea0a32f9535fff83b00a0a574)).
Thanks to add that.

**Comment by diwic** [comment]
Hmm, yes, it requires some careful thinking though...we used to have that in PulseAudio, but I rewrote it to use a mixer class instead; this was in order to catch both jack events (plug/unplug headphone) and mixer events for the same handle. Maybe that's what we're supposed to support instead...?

**Comment by antoyo** [comment]
Which PulseAudio crate do you talk about?

**Comment by diwic** [comment]
I'm not talking about a crate - I'm talking about the PulseAudio sound server itself, which I used to help maintaining.

**Comment by diwic** [comment]
@antoyo Going through old issues and found this one. Do you still need the callback? Callbacks from C to Rust is always non-trivial; but I guess we could do an "abort on panic" and use "set_callback_private" to store the environment for a closure...?

**Comment by antoyo** [comment]
I don't need that anymore.
