### ISSUE TITLE
No snd_ctl_subscribe_events()?

### ISSUE THREAD

**Issue by Ploppz** [diwic/alsa-rs#29]
Can't find it in docs, and searched in the source code. There seems to be no way to subscribe to events with `snd_ctl_subscribe_events`.
What I want to do is to wait for events, then get volume information. Waiting for events can be done like this in C:
```
    const char *ctlname = "default";
    snd_ctl_t *ctl;
    assert( snd_ctl_open(&ctl, ctlname, SND_CTL_READONLY) == 0 );
    assert( snd_ctl_subscribe_events(ctl, 1) == 0 );

    struct pollfd* fd = malloc(sizeof(struct pollfd));
    snd_ctl_poll_descriptors(ctl, fd, 1);


    while (1) {
        err = poll(fd, 1, -1);
        while (snd_ctl_read(ctl, event) > 0) {
                 ..... etc .....
```

**Comment by diwic** [comment]
Hi, I just pushed a commit that adds the functions you asked for. Could you have a look and see if it works according to your expectations?

**Comment by Ploppz** [comment]
Yes it works perfectly. Thank you very much!

**Comment by diwic** [comment]
@Ploppz  Thanks, do you need a release as well?

**Comment by Ploppz** [comment]
That would be nice, yes please

**Comment by diwic** [comment]
@Ploppz done now, enjoy!
