### ISSUE TITLE
set volume: do we need mixer interface?

### ISSUE THREAD

**Issue by lrbalt** [diwic/alsa-rs#3]
I've been looking at the alsa api to use the mixer to set volume of individual channels. Do we need to add a wrapper for the `snd_mixer_*` and/or `snd_mixer_selem_*`?

**Comment by diwic** [comment]
Indeed the [simple mixer interface](http://www.alsa-project.org/alsa-doc/alsa-lib/group___simple_mixer.html) is the most important missing piece in alsa-rs right now.

Is it something you'd like to work on yourself? Otherwise I'll do it, but I can't promise it'll be done this week.

**Comment by lrbalt** [comment]
I'd like to give it a try. I'm just learning ALSA API, so you'll probably need to review it :-)

**Comment by diwic** [comment]
Okay, go ahead :-) Tip: have a look at [amixer.c:selems](http://git.alsa-project.org/?p=alsa-utils.git;a=blob;f=amixer/amixer.c;h=f9b09cb54276dbb88c5abc6b197727e8fd58b8eb;hb=HEAD#l1029) to get an idea of what ALSA functions you need to add to get something up and running. Skip everything `snd_mixer_elem_*` for now, all we need is the `snd_mixer_selem_*`, and some `snd_mixer_*` to support that.

**Comment by lrbalt** [comment]
Yes, thanks. I have some rust code working that uses alsa-sys directly to get volume parameters of 8 channels. I'll try to use your code for hclt as inspiration to get to an iterator en getters/setters. I hope to get some time this weekend. I'll create a PR to discuss the code

**Comment by lrbalt** [comment]
closing because of existing PR.
