### ISSUE TITLE
0.2.0 breaks pcm.recover use case

### ISSUE THREAD

**Issue by Paspartout** [diwic/alsa-rs#30]
On updating alsa-rs to 0.2.0 I noticed that you changed the way errors are handled now.
While I think the nix package provides a nice way of representing the errno in rust, I unfortunately don't see a nice way how to use [pcm.recover()](https://docs.rs/alsa/0.2.0/alsa/pcm/struct.PCM.html#method.recover), which needs the original error code as an integer value.

Maybe it's a good idea to add the error code together with the code() method back to the Error struct to be able to use recover, or is there a better way of doing this?
Alternatively I could probably map nix::errno::{EINTR,EPIPE,ESTRPIPE} back to the libc:: values myself.

**Comment by diwic** [comment]
> Alternatively I could probably map nix::errno::{EINTR,EPIPE,ESTRPIPE} back to the libc:: values myself.

...and doing that should be as simple as `alsaerr.errno().map(|x| x as c_int)`, I believe. But maybe I could add a small wrapper that does just that.

**Comment by diwic** [comment]
Could you try `pcm.try_recover` (just added) to see if it does what you expect it to? Thanks.
