### ISSUE TITLE
Suggestion: Add ability to create IO instances from PCMs generically

### ISSUE THREAD

**Issue by tronje** [diwic/alsa-rs#56]
Hi! I was trying to generically create an instance of the `IO` struct from an instance of `PCM`, depending on which format is being used. This is currently not easily possible, as something like
```rust
let io = pcm.io::<u32>()?;
```
is not possible. The reason is, of course, that the different `PCM::io_*` methods perform checks based on instances of the `Format` enum [here](https://docs.rs/alsa/0.4.2/src/alsa/pcm.rs.html#190).

So I ended up implementing a trait like this:

```rust
use alsa::pcm::{IO, PCM};

trait IoFromPcm: Copy {
    fn io_from_pcm<'a>(pcm: &'a PCM) -> alsa::Result<IO<Self>>;
}

impl IoFromPcm for u8 {
    fn io_from_pcm<'a>(pcm: &'a PCM) -> alsa::Result<IO<Self>> {
        pcm.io_u8()
    }
}

impl IoFromPcm for i8 {
    fn io_from_pcm<'a>(pcm: &'a PCM) -> alsa::Result<IO<Self>> {
        pcm.io_i8()
    }
}

// and so on for u16, i16, u32, i32, f32, and f64
```

and then doing something like this in my application code:

```rust
fn play_something<T: IoFromPcm>(&self, buf: &[T]) -> alsa::Result<()> {
    let io = T::io_from_pcm(&self.pcm)?;
    io.writei(&buf)?;

    // ...
}
```
(The above is greatly abridged, not sure if that would really compile, but I think you get the idea).

Maybe it would be cool to add a similar mechanism to the library, to make it easier to dynamically choose a format for the IO instance?

**Comment by diwic** [comment]
Hi!

I think this is an excellent suggestion! Do you want to submit a PR or would you prefer if I implemented it myself?

**Comment by diwic** [comment]
Hmm, hard to not start to think about how I want to do this, I

**Comment by diwic** [comment]
Ok, I've implemented a new method `pcm::io_checked` that is generic, let me know what you think!

**Comment by tronje** [comment]
I like it! Thanks a lot for taking the time to implement it! :smiley:
