### ISSUE TITLE
include license in crate source

### ISSUE THREAD

**Issue by remilauzier** [diwic/alsa-rs#70]
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by diwic** [comment]
Hi,

I'm the maintainer of alsa-rs itself (i e the "upstream"), not the Fedora packaging of alsa-rs. Did you post this in the wrong place?

If not: I'm happy to collaborate, e g by reviewing and merge PRs to make packaging in distros easier, but if you're just posting links from a distro's packaging guidelines and expecting me to do read, understand and abide, that's not okay.

**Comment by remilauzier** [comment]
I am the one who want to package alsa-rs to fedora, there is no mistake here. I thought the headline was enough but fedora need the LICENSE file include in the crate source. ``include = ["LICENSE", etc]``
I put the link because some want to see them to better understand what is need to do.

**Comment by diwic** [comment]
Okay, feel free to submit a PR that fixes what you think needs to be fixed and we'll take it from there.
