### ISSUE TITLE
test failed in fedora copr

### ISSUE THREAD

**Issue by remilauzier** [diwic/alsa-rs#71]
https://download.copr.fedorainfracloud.org/results/remilauzier/zemeroth/fedora-rawhide-x86_64/02304631-rust-alsa/builder-live.log.gz

failures:

---- src/pcm.rs - pcm (line 6) stdout ----
Test executable failed (exit code 101).

stderr:
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("snd_pcm_open", Sys(ENOENT))', src/pcm.rs:8:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by remilauzier** [comment]
Did you close it because the bugs is not on your fault? I need to know what can be do.

**Comment by remilauzier** [comment]
Sorry didn't see the commit that fix it.

**Comment by diwic** [comment]
@remilauzier You need to configure the environment that the tests are run in, to contain at least one sound card capable of playback and record.

**Comment by remilauzier** [comment]
Nah. Will need to let the test deactivate since fedora compiled the package in a CI. I am not sure there's even a fake sound card that can be use.
