### ISSUE TITLE
Microphone recording example?

### ISSUE THREAD

**Issue by beckend** [diwic/alsa-rs#85]

**Comment by diwic** [comment]
For now there is some test code here: https://github.com/diwic/alsa-rs/blob/master/src/pcm.rs#L1031

**Comment by diwic** [comment]
Fixed now: https://github.com/diwic/alsa-rs/blob/master/examples/record.rs

**Comment by beckend** [comment]
Thank you, I however tried to open it in non blocking mode to write buffers, it gives me:
```shell
`Err` value: Error("snd_pcm_readi", Sys(EAGAIN))'
```
Why is that?

**Comment by beckend** [comment]
Never mind I got it working by polling the fds.
