### ISSUE TITLE
missing snd_ctl_elem_read, snd_ctl_elem_write

### ISSUE THREAD

**Issue by srperens** [diwic/alsa-rs#87]
Hi, are there any plans to add snd_ctl_elem_read and snd_ctl_elem_write functions ?

I would like to be able to do from safe rust basically what this command does:

amixer -c 0 cset numid=26 64,4,0

Please see https://fossies.org/linux/alsa-utils/amixer/amixer.c @ line 1128 for amixer cset function. 

Thanks!

**Comment by diwic** [comment]
I'll be happy to take a PR that adds these, go ahead!

**Comment by srperens** [comment]
Thanks for info.

We'll see if we return to this in the future, in that case there will be a PR. :)
