### ISSUE TITLE
`alsa::seq::EventData::get_data` feels unsafe

### ISSUE THREAD

**Issue by NeoGalaxy** [diwic/alsa-rs#95]
I'm rewriting a C utility in Rust using alsa, and when looking at `alsa::seq::EventData::get_data`'s content it feels like it is meant to do an unchecked cast. Shouldn't it be marked as unsafe? It feels inherently unsafe to me.

Additionally, you tell us "Don’t use these directly, use generic methods on Event instead". It seems like you tell this so we don't miss-use `get_data`, as using it in the wrong context can lead to UB, if I understood correctly. So making it unsafe feels right to me.

**Comment by diwic** [comment]
If you misuse `get_data` you will get wrong data, but it would not be UB to do so. 

E g, if you have a note event and call `EvQueueControl<Duration>::get_data` on that note, you might get a duration of a trillion years. Or your code might even panic. But you would never get UB. 

Hence, `get_data` should not be marked as `unsafe`, unless you have an example in more detail how this could happen?

**Comment by NeoGalaxy** [comment]
Sorry, didn't see you answered.

True, I jumped too quickly to conclusions. My base idea is that, to use `get_data`, one should first check the type of the content. Marking it as unsafe can say "dear user, you have to check a contract before using this function", as suggested in the [Rust book](https://doc.rust-lang.org/std/keyword.unsafe.html#the-different-meanings-of-unsafe). So talking about UB was sudden and unclear of me, sorry. And yes you're right, I don't seem to be able to get a UB in any way.

 Still, I think this "contract" idea is still good enough of a reason. It literally writes the warning you wrote in the docs/comments directly into the code. But it's more of a subjective preference, so it's up to you

**Comment by diwic** [comment]
I chose to hide them from documentation instead.

**Comment by NeoGalaxy** [comment]
Oh, ok. It's indeed in the same idea of the comment
